// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/code-editor/index.vue')['default']
    DragCard: typeof import('./src/components/drag-temp/drag-card.vue')['default']
    DragTemp: typeof import('./src/components/drag-temp/index.vue')['default']
    Drawer: typeof import('./src/components/drawer/index.vue')['default']
    FlexBox: typeof import('./src/components/flex-box/index.vue')['default']
    FreeLayout: typeof import('./src/components/free-layout/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImgPreview: typeof import('./src/components/img-preview/index.vue')['default']
    LayoutItem: typeof import('./src/components/free-layout/layout-item.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    ResizeBox: typeof import('./src/components/resize-box/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollText: typeof import('./src/components/scroll-text/index.vue')['default']
  }
}
